# Data Importing and Understanding

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("saicharankomati/dataco-supply-chain-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/saicharankomati/dataco-supply-chain-dataset/1.archive...

100%|██████████| 17.8M/17.8M [00:00<00:00, 116MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/saicharankomati/dataco-supply-chain-dataset/versions/1

In [ ]:
import os
import pandas as pd

csv_file = os.path.join(path,"DataCoSupplyChainDataset.csv")

df = pd.read_csv(csv_file,encoding="latin-1") #File uses latin-1 encoding instead of utf-8(regular one)

df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [ ]:
df.shape

(180519, 53)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [ ]:
df.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [ ]:
df.isnull().sum()[df.isnull().sum() > 0]

Customer Lname              8
Customer Zipcode            3
Order Zipcode          155679
Product Description    180519
dtype: int64

# Data Cleaning and Preprocessing

In [ ]:
cols = [
    "Order Id", "order date (DateOrders)", "shipping date (DateOrders)",
    "Days for shipping (real)", "Days for shipment (scheduled)",
    "Delivery Status", "Shipping Mode", "Order Region", "Order Country",
    "Order State", "Category Name", "Sales", "Order Profit Per Order",
    "Order Item Quantity"
]

In [ ]:
df = df[cols]

print(df.shape)
df.columns

(180519, 14)

Index(['Order Id', 'order date (DateOrders)', 'shipping date (DateOrders)',
       'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Delivery Status', 'Shipping Mode', 'Order Region', 'Order Country',
       'Order State', 'Category Name', 'Sales', 'Order Profit Per Order',
       'Order Item Quantity'],
      dtype='object')

In [ ]:
df.columns = [
    "order_id", "order_date", "ship_date", "days_actual",
    "days_scheduled", "delivery_status", "ship_mode", "region",
    "country", "state", "category", "sales", "profit", "quantity"
]

print(df.columns)
df.shape

Index(['order_id', 'order_date', 'ship_date', 'days_actual', 'days_scheduled',
       'delivery_status', 'ship_mode', 'region', 'country', 'state',
       'category', 'sales', 'profit', 'quantity'],
      dtype='object')

(180519, 14)

In [ ]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["ship_date"] = pd.to_datetime(df["ship_date"])

print(df["order_date"].dtype)
print(df["ship_date"].dtype)

datetime64[ns]
datetime64[ns]

In [ ]:
df["delay_days"] = df["days_actual"] - df["days_scheduled"]
df["is_late"] = df["delay_days"] > 0
df["profit_margin"] = (df["profit"] / df["sales"]) * 100
df["order_month"] = df["order_date"].dt.to_period("M").astype(str)

In [ ]:
df.dropna(subset=["order_date", "ship_date", "delivery_status"], inplace=True)
df.to_csv("supplychain_clean.csv", index=False)

# EDA

In [ ]:
# Distribution of Delivery Status
print(df["delivery_status"].value_counts())
print()

# Distribution of Shipping mode
print(df["ship_mode"].value_counts())
print()

# On-time rate
on_time_rate = (df["is_late"] == False).sum() / len(df) * 100
print(f"On-time delivery rate: {on_time_rate:.1f}%")
print()

# Average delay
print(f"Avg delay days: {df['delay_days'].mean():.1f}")
print()

# Profit margin summary
print(f"Avg profit margin: {df['profit_margin'].mean():.1f}%")

delivery_status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

ship_mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

On-time delivery rate: 42.7%

Avg delay days: 0.6

Avg profit margin: 10.8%

In [ ]:
print(df["ship_mode"].value_counts())

ship_mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

In [ ]:
#Saving it to a csv, easy for downloading
df.to_csv("supplychain_clean.csv", index=False)

# Downloading file
from google.colab import files
files.download("supplychain_clean.csv")